### PR TITLE
Remove comment to trigger CI

### PR DESCRIPTION
**Pull request by a4z**

### CODE REVIEW

**Comment by ZhongRuoyu** [comment]
It seems that GitHub Actions is unable to close your PR. To allow it to close published PRs automatically in the future, can you try changing the `pull-requests` permission to `pull-requests: write`?

(Sorry for the back and forth. I will look into improving this.)

**Comment by a4z** [comment]
> (Sorry for the back and forth. I will look into improving this.)

Please don't apologize, you help me so much, you are awesome! 

I add one more run, need then to rest, in my part of the world it's already late.

**Comment by a4z** [comment]
Needed to restart the PR with a clean history, since there was some cherry pick issue in the actions, but [No 5](https://github.com/a4z/homebrew-cpp-taps/pull/5) worked :-) 
First success before going to bed, nice. Thanks for the help!!

**Comment by ZhongRuoyu** [comment]
No problem! Glad it worked for you. Yes, merge commits (`git merge main`) are not easy to cope with; rebase should work better.

**Pull request closed without merging**
